# https://github.com/AnimMouse/setup-rclone
name: scheduled

on:
  push:
    branches:
      - develop

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}
        
      - name: Add Rclone service account file
        uses: AnimMouse/setup-rclone/service-account-file@v1
        with:
          service_account_filename: service-account-file.json
          service_account_file: ${{ secrets.SERVICE_ACCOUNT_FILE }}
        
      - run: rclone copy sm2drive:Vzduchotechnika/Latest/ ./latest/

      - run: ls -l ./latest/

      - name: Iterate over files and extract SM house number and date
        run: |
          for file in ./latest/*; do
            echo "Processing $file"
            sm_house_number=$(head -n 1 "$file" | grep "Date" | grep -Eo 'vzt[0-9]{2}_temp-tea-sani' | grep -Eo '[0-9]{2}')
            echo "SM House Number: $sm_house_number"
            date=$(tail "$file" | grep "00:00" | tail -n 1 | grep -Eo '[0-9]{2}.[0-9]{2}.[0-9]{4} [0-9]{2}:[0-9]{2}:[0-9]{2}' | sed -E 's/([0-9]{2}).([0-9]{2}).([0-9]{4})/\3-\2-\1/')
            echo "Date: $date"
            if [[ ${#sm_house_number} -eq 2 ]]; then
              mv "$file" "./latest/sm${sm_house_number}_${date//[\ \:\-\;><\@\$\#\&\(\)\?\\\/\%]/_}.csv"
            else
              echo "Skipping renaming $file as SM house number does not have exactly two characters."
            fi
          done
      
      - run: ls -l ./latest/